# file: C:\Users\David\AppData\Roaming\Python\Python312\site-packages\_pytest\_code\code.py
# hypothesis_version: 6.131.17

[', ', '-', '<', '>', '???', '@', 'AssertionError: ', 'E', 'HTTPError', '_ ', '__builtins__', '__init__.py', '__notes__', '__tracebackhide__', '_rawentry', '_repr_style', 'auto', 'line', 'long', 'msg', 'native', 'no', 'no current exception', 'oc', 'path check failed.', 'place_as', 'raw', 'short', 'urllib.error', 'value', '{}\n{}\n{}']